apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: java-quarkus-lbmzurst
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/java-quarkus-lbmzurst:7b5aabcd280fd40bd825180b246de44e1d289d20@sha256:0caf82380ef546aee563e3c490c898ac57b09af2d1e60e01490479ce37352e3a
          name: container-image
